apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # Tell cert-manager to create an SSL certificate via LetsEncrypt
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'True'
  labels:
    app: voting-booth
  name: voting-booth-ingress
  namespace: voting-booth
spec:
  backend:
    serviceName: voting-booth-service
    servicePort: 4201
  rules:
  - host: voting-booth.dokube.profortool.com
    http:
      paths:
      - backend:
          serviceName: voting-booth-service
          servicePort: 4201
  tls:
  - secretName: voting-booth-certificate
    hosts:
    - voting-booth.dokube.profortool.com
