# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voting-booth
  name: voting-booth
  namespace: voting-booth
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: voting-booth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: voting-booth
    spec:
      containers:
      - image: eu.gcr.io/proforto-team-sso/voting-booth:16.5
        imagePullPolicy: Always
        name: voting-booth
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
      restartPolicy: Always
